In [4]:
import torch
data = [[[1, 2],[3, 0]], [[1, 2],[4, 0]]]
x_data = torch.tensor(data)
0.8*torch.ones_like(x_data)

tensor([[[0.8000, 0.8000],
         [0.8000, 0.8000]],

        [[0.8000, 0.8000],
         [0.8000, 0.8000]]])

In [1]:
assert isinstance(x_data, torch.Tensor)

NameError: name 'x_data' is not defined

In [21]:
x_data.sum(2)

tensor([[3, 3],
        [3, 4]])

In [22]:
torch.cat?

Docstring:
cat(tensors, dim=0, *, out=None) -> Tensor

Concatenates the given sequence of :attr:`seq` tensors in the given dimension.
All tensors must either have the same shape (except in the concatenating
dimension) or be empty.

:func:`torch.cat` can be seen as an inverse operation for :func:`torch.split`
and :func:`torch.chunk`.

:func:`torch.cat` can be best understood via examples.

Args:
    tensors (sequence of Tensors): any python sequence of tensors of the same type.
        Non-empty tensors provided must have the same shape, except in the
        cat dimension.
    dim (int, optional): the dimension over which the tensors are concatenated

Keyword args:
    out (Tensor, optional): the output tensor.

Example::

    >>> x = torch.randn(2, 3)
    >>> x
    tensor([[ 0.6580, -1.0969, -0.4614],
            [-0.1034, -0.5790,  0.1497]])
    >>> torch.cat((x, x, x), 0)
    tensor([[ 0.6580, -1.0969, -0.4614],
            [-0.1034, -0.5790,  0.1497],
            [ 0.6580, -1.0969,

In [10]:

from IPython.core import debugger as ipdb
import os

import numpy as np
import pandas as pd
from itertools import chain

import sys
import time
import trainer_alpha
import torch
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

import os
from pathlib import Path
import paus_sexp as paus_data

from matplotlib import pyplot as plt
import utils

import local_settings
import loaders

loaded path /nfs/pic.es/user/i/idazaper/deepz/deepz/arch_mdn.py


**Mis corridas**

- Con el entorno lacegal:

    keep_last True alpha 0.8 sig68 0.0005762075888924301
    
- Con el enterno deepz:

    keep_last True alpha 0.8 sig68 0.006400951901450753